SQL> 
SQL> --2. List all patients with all their addresses.
SQL> 
SQL> SELECT Person_ID, Person_Name, Person_Age, Person_Gender, Person_Type, Patient_Type, Country, Zone, City, Street, Street_Number
  2  FROM Patient
  3  JOIN Person
  4  USING (Person_ID)
  5  JOIN Address
  6  USING (Person_ID);

 PERSON_ID PERSON_NAME          PERSON_AGE PERSON PERSON_TYPE  PATIENT_TYPE                   COUNTRY              ZONE                 CITY                 STREET               STREET_NUMBER                                                                                                                                                                                                                                                                                                                     
---------- -------------------- ---------- ------ ------------ ------------------------------ -------------------- -------------------- -------------------- -------------------- -------------                                                                                                                                                                                                                                                                                                                     
         1 Raj Gurung                   25 Male   Patient      New                            Nepal                Bagmati              Kathmandu            Tokha Sadak                      8                                                                                                                                                                                                                                                                                                                     
         2 Anurag Dhungana              26 Male   Patient      New                            Nepal                Bagmati              Kathmandu            Lekhnath Sadak                  11                                                                                                                                                                                                                                                                                                                     
         3 Shuvechha Shrestha           24 Female Patient      Regular                        Nepal                Bagmati              Kathmandu            Ganesh Dev Marg                 10                                                                                                                                                                                                                                                                                                                     
         4 Sushant Chhetri              28 Male   Patient      Regular                        Nepal                Bagmati              Kathmandu            Embassy Marg                     4                                                                                                                                                                                                                                                                                                                     
         6 Roshan Rhymaji               36 Male   Doctor       Regular_Uncertified_Doctor     Nepal                Bagmati              Lalitpur             Dhapakhel Sadak                  2                                                                                                                                                                                                                                                                                                                     
         7 Ram Kumar Shrestha           46 Male   Doctor       New_Certified_Doctor           Nepal                Bagmati              Lalitpur             Sheetal Tole                    13                                                                                                                                                                                                                                                                                                                     
         9 Binita Maharjan              26 Female Nurse        New_Uncertified_Nurse          Nepal                Bagmati              Bhaktapur            Purano Bato                      6                                                                                                                                                                                                                                                                                                                     
        12 Shikha KC                    25 Female Nurse        Regular_Certified_Nurse        Nepal                Lumbini              Tansen               Basantapur Marg                  3                                                                                                                                                                                                                                                                                                                     
        12 Shikha KC                    25 Female Nurse        Regular_Certified_Nurse        Nepal                Bagmati              Kathmandu            Devkota Sadak                    3                                                                                                                                                                                                                                                                                                                     

9 rows selected.

SQL> 